# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_session = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_session.setObjectName("lineEdit_session")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_session)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_appid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_appid.setObjectName("lineEdit_appid")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_appid)
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DateEdit_start = QtWidgets.QDateEdit(self.centralwidget)
        self.DateEdit_start.setObjectName("DateEdit_start")
        self.horizontalLayout_3.addWidget(self.DateEdit_start)
        self.DateEdit_end = QtWidgets.QDateEdit(self.centralwidget)
        self.DateEdit_end.setObjectName("DateEdit_end")
        self.horizontalLayout_3.addWidget(self.DateEdit_end)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_2.addWidget(self.pushButton_run)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.verticalLayout.addWidget(self.plainTextEdit_log)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "微信小游戏采集"))
        self.label.setText(_translate("MainWindow", "session"))
        self.label_2.setText(_translate("MainWindow", "appid"))
        self.Label_2.setText(_translate("MainWindow", "时间段"))
        self.pushButton_run.setText(_translate("MainWindow", "开始"))
